-- =============================================
-- BACKUP: Old Supabase Schema (Financial/Compliance System)
-- Project: lsedtoznehxdnxlqmccm (flow_prompter - to be replaced)
-- Generated: 2025-01-09
-- =============================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================
-- TABLES
-- =============================================

CREATE TABLE tenants (
  id UUID NOT NULL DEFAULT uuid_generate_v4(),
  name VARCHAR(200) NOT NULL,
  fsp_number VARCHAR(50) NOT NULL,
  logo_url TEXT,
  settings JSONB DEFAULT '{}'::jsonb,
  subscription_tier VARCHAR(50) DEFAULT 'starter'::character varying,
  subscription_status VARCHAR(50) DEFAULT 'active'::character varying,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  is_deleted BOOLEAN DEFAULT false,
  deleted_at TIMESTAMP WITH TIME ZONE,
  deleted_by UUID,
  deletion_reason TEXT,
  PRIMARY KEY (id)
);

CREATE TABLE advisors (
  id UUID NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id UUID NOT NULL,
  auth_user_id UUID,
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(20),
  avatar_url TEXT,
  role VARCHAR(50) NOT NULL DEFAULT 'advisor'::character varying,
  permissions JSONB DEFAULT '{}'::jsonb,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  is_deleted BOOLEAN DEFAULT false,
  deleted_at TIMESTAMP WITH TIME ZONE,
  deleted_by UUID,
  deletion_reason TEXT,
  PRIMARY KEY (id)
);

CREATE TABLE clients (
  id UUID NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id UUID NOT NULL,
  primary_advisor_id UUID,
  auth_user_id UUID,
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  email VARCHAR(255),
  phone VARCHAR(20),
  date_of_birth DATE,
  id_number VARCHAR(50),
  passport_number VARCHAR(50),
  tax_number VARCHAR(50),
  physical_address TEXT,
  postal_address TEXT,
  client_code VARCHAR(50),
  client_status VARCHAR(50) DEFAULT 'active'::character varying,
  onboarding_stage VARCHAR(50),
  source VARCHAR(100),
  risk_profile VARCHAR(50),
  investment_objectives TEXT,
  fica_status VARCHAR(50),
  fica_completed_date DATE,
  fica_expiry_date DATE,
  fica_risk_score INTEGER,
  fica_risk_classification VARCHAR(50),
  estimated_net_worth NUMERIC(20,2),
  annual_income NUMERIC(20,2),
  preferred_contact_method VARCHAR(50),
  portal_access_enabled BOOLEAN DEFAULT true,
  email_notifications_enabled BOOLEAN DEFAULT true,
  whatsapp_notifications_enabled BOOLEAN DEFAULT false,
  mandate_signed_date DATE,
  first_investment_date DATE,
  last_review_date DATE,
  next_review_date DATE,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  is_deleted BOOLEAN DEFAULT false,
  deleted_at TIMESTAMP WITH TIME ZONE,
  deleted_by UUID,
  deletion_reason TEXT,
  occupation VARCHAR(200),
  employer VARCHAR(200),
  employment_status VARCHAR(50),
  marital_status VARCHAR(50),
  spouse_name VARCHAR(200),
  spouse_email VARCHAR(255),
  spouse_phone VARCHAR(20),
  spouse_dob DATE,
  anniversary_date DATE,
  dependents JSONB DEFAULT '[]'::jsonb,
  beneficiaries JSONB DEFAULT '[]'::jsonb,
  retirement_age_target INTEGER,
  retirement_income_monthly NUMERIC(15,2),
  financial_goals JSONB DEFAULT '[]'::jsonb,
  linkedin_url VARCHAR(500),
  facebook_url VARCHAR(500),
  instagram_handle VARCHAR(100),
  twitter_handle VARCHAR(100),
  work_phone VARCHAR(20),
  mobile_phone VARCHAR(20),
  home_phone VARCHAR(20),
  emergency_contact_name VARCHAR(200),
  emergency_contact_phone VARCHAR(20),
  emergency_contact_relationship VARCHAR(100),
  professional_designation VARCHAR(100),
  industry VARCHAR(100),
  years_in_profession INTEGER,
  hobbies TEXT,
  interests TEXT,
  languages_spoken VARCHAR(200),
  birthday_month INTEGER,
  birthday_day INTEGER,
  review_frequency VARCHAR(50),
  preferred_meeting_location VARCHAR(200),
  preferred_meeting_time VARCHAR(50),
  newsletter_weekly BOOLEAN DEFAULT true,
  newsletter_monthly BOOLEAN DEFAULT true,
  sms_notifications_enabled BOOLEAN DEFAULT false,
  will_last_updated DATE,
  estate_executor VARCHAR(200),
  trust_structures JSONB DEFAULT '[]'::jsonb,
  tax_residence VARCHAR(100),
  foreign_tax_id VARCHAR(100),
  tax_filing_status VARCHAR(50),
  liquid_net_worth NUMERIC(20,2),
  total_liabilities NUMERIC(20,2),
  monthly_expenses NUMERIC(15,2),
  PRIMARY KEY (id)
);

CREATE TABLE lisp_platforms (
  id UUID NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id UUID NOT NULL,
  name VARCHAR(200) NOT NULL,
  platform_type VARCHAR(100),
  integration_method VARCHAR(50),
  logo_url TEXT,
  website VARCHAR(255),
  api_base_url TEXT,
  api_auth_method VARCHAR(50),
  api_credentials_encrypted TEXT,
  api_rate_limit_per_minute INTEGER,
  csv_format_identifier TEXT,
  csv_parser_version VARCHAR(20),
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  is_deleted BOOLEAN DEFAULT false,
  deleted_at TIMESTAMP WITH TIME ZONE,
  deleted_by UUID,
  deletion_reason TEXT,
  PRIMARY KEY (id)
);

CREATE TABLE portfolios (
  id UUID NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id UUID NOT NULL,
  client_id UUID NOT NULL,
  advisor_id UUID,
  platform_id UUID,
  portfolio_name VARCHAR(200),
  portfolio_code VARCHAR(50),
  platform VARCHAR(100),
  account_number VARCHAR(200),
  platform_account_id VARCHAR(200),
  platform_account_name VARCHAR(200),
  portfolio_type VARCHAR(100),
  currency VARCHAR(3) DEFAULT 'ZAR'::character varying,
  inception_date DATE,
  maturity_date DATE,
  status VARCHAR(50) DEFAULT 'active'::character varying,
  last_sync_date DATE,
  last_updated TIMESTAMP WITH TIME ZONE,
  last_sync_method VARCHAR(50),
  last_sync_status VARCHAR(50),
  last_sync_error TEXT,
  current_market_value NUMERIC(20,2),
  cost_base NUMERIC(20,2),
  total_cost_base NUMERIC(20,2),
  unrealized_gain_loss NUMERIC(20,2),
  unrealized_gain_loss_pct NUMERIC(10,4),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  is_deleted BOOLEAN DEFAULT false,
  deleted_at TIMESTAMP WITH TIME ZONE,
  deleted_by UUID,
  deletion_reason TEXT,
  PRIMARY KEY (id)
);

CREATE TABLE holdings (
  id UUID NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id UUID NOT NULL,
  portfolio_id UUID NOT NULL,
  isin VARCHAR(50),
  ticker VARCHAR(20),
  security_name VARCHAR(200) NOT NULL,
  asset_class VARCHAR(100),
  sector VARCHAR(100),
  geographic_exposure VARCHAR(100),
  units NUMERIC(20,8),
  avg_cost_per_unit NUMERIC(20,4),
  current_price NUMERIC(20,4),
  price_currency VARCHAR(3) DEFAULT 'ZAR'::character varying,
  total_cost NUMERIC(20,2),
  market_value NUMERIC(20,2),
  unrealized_gain_loss NUMERIC(20,2),
  unrealized_gain_loss_pct NUMERIC(10,4),
  allocation_percentage NUMERIC(5,2),
  dividend_yield NUMERIC(5,4),
  last_dividend_date DATE,
  last_dividend_amount NUMERIC(20,4),
  last_price_date TIMESTAMP WITH TIME ZONE,
  last_price_update TIMESTAMP WITH TIME ZONE,
  price_source VARCHAR(100),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  is_deleted BOOLEAN DEFAULT false,
  deleted_at TIMESTAMP WITH TIME ZONE,
  deleted_by UUID,
  deletion_reason TEXT,
  PRIMARY KEY (id)
);

CREATE TABLE transactions (
  id UUID NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id UUID NOT NULL,
  portfolio_id UUID NOT NULL,
  holding_id UUID,
  transaction_date DATE NOT NULL,
  settlement_date DATE,
  transaction_type VARCHAR(50) NOT NULL,
  isin VARCHAR(50),
  ticker VARCHAR(20),
  security_name VARCHAR(200),
  units NUMERIC(20,8),
  price NUMERIC(20,4),
  gross_amount NUMERIC(20,2),
  fees NUMERIC(20,2),
  brokerage_fee NUMERIC(20,2),
  advisor_fee NUMERIC(20,2),
  platform_fee NUMERIC(20,2),
  vat NUMERIC(20,2),
  stt NUMERIC(20,2),
  withholding_tax NUMERIC(20,2),
  other_fees NUMERIC(20,2),
  net_amount NUMERIC(20,2),
  currency VARCHAR(3) DEFAULT 'ZAR'::character varying,
  exchange_rate NUMERIC(20,8),
  description TEXT,
  external_reference VARCHAR(200),
  import_batch_id UUID,
  imported_from VARCHAR(100),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  is_deleted BOOLEAN DEFAULT false,
  deleted_at TIMESTAMP WITH TIME ZONE,
  deleted_by UUID,
  deletion_reason TEXT,
  PRIMARY KEY (id)
);

CREATE TABLE portfolio_reports (
  id UUID NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id UUID NOT NULL,
  client_id UUID NOT NULL,
  advisor_id UUID,
  report_type VARCHAR(100) NOT NULL,
  report_period_start DATE NOT NULL,
  report_period_end DATE NOT NULL,
  report_title VARCHAR(255),
  status VARCHAR(50) DEFAULT 'generating'::character varying,
  ai_commentary TEXT,
  ai_model VARCHAR(50),
  ai_prompt_version VARCHAR(20),
  ai_generation_time_ms INTEGER,
  ai_token_count INTEGER,
  data_snapshot JSONB,
  portfolio_value_start NUMERIC(20,2),
  portfolio_value_end NUMERIC(20,2),
  net_contributions NUMERIC(20,2),
  investment_return NUMERIC(20,2),
  investment_return_pct NUMERIC(10,4),
  benchmark_name VARCHAR(100),
  benchmark_return_pct NUMERIC(10,4),
  relative_performance_pct NUMERIC(10,4),
  pdf_url TEXT,
  html_url TEXT,
  excel_url TEXT,
  generated_by UUID,
  generated_at TIMESTAMP WITH TIME ZONE,
  reviewed_by UUID,
  reviewed_at TIMESTAMP WITH TIME ZONE,
  approved_by UUID,
  approved_at TIMESTAMP WITH TIME ZONE,
  sent_at TIMESTAMP WITH TIME ZONE,
  client_viewed_at TIMESTAMP WITH TIME ZONE,
  client_feedback TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  is_deleted BOOLEAN DEFAULT false,
  deleted_at TIMESTAMP WITH TIME ZONE,
  deleted_by UUID,
  deletion_reason TEXT,
  PRIMARY KEY (id)
);

CREATE TABLE fica_submissions (
  id UUID NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id UUID NOT NULL,
  client_id UUID NOT NULL,
  cdd_type VARCHAR(50) NOT NULL,
  full_names VARCHAR(255),
  surname VARCHAR(100),
  id_number VARCHAR(50),
  passport_number VARCHAR(50),
  date_of_birth DATE,
  nationality VARCHAR(100),
  country_of_residence VARCHAR(100),
  physical_address TEXT,
  postal_address TEXT,
  phone VARCHAR(20),
  email VARCHAR(255),
  source_of_wealth TEXT,
  source_of_income TEXT,
  employer VARCHAR(200),
  occupation VARCHAR(200),
  company_name VARCHAR(200),
  company_registration_number VARCHAR(100),
  company_tax_number VARCHAR(100),
  ubo_details JSONB,
  risk_score INTEGER,
  risk_classification VARCHAR(50),
  risk_factors JSONB,
  cash_transaction_threshold_breached BOOLEAN DEFAULT false,
  cash_transaction_amount NUMERIC(20,2),
  cash_transaction_reason TEXT,
  id_document_url TEXT,
  proof_of_residence_url TEXT,
  bank_statement_url TEXT,
  tax_clearance_url TEXT,
  other_documents_urls JSONB,
  verification_method VARCHAR(100),
  verification_date DATE,
  verified_by UUID,
  status VARCHAR(50) DEFAULT 'pending'::character varying,
  submission_date TIMESTAMP WITH TIME ZONE,
  review_date TIMESTAMP WITH TIME ZONE,
  approval_date TIMESTAMP WITH TIME ZONE,
  expiry_date DATE,
  reviewed_by UUID,
  reviewer_notes TEXT,
  rejection_reason TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  is_deleted BOOLEAN DEFAULT false,
  deleted_at TIMESTAMP WITH TIME ZONE,
  deleted_by UUID,
  deletion_reason TEXT,
  PRIMARY KEY (id)
);

CREATE TABLE compliance_audit_log (
  id UUID NOT NULL DEFAULT uuid_generate_v4(),
  tenant_id UUID NOT NULL,
  table_name TEXT NOT NULL,
  record_id UUID NOT NULL,
  action TEXT NOT NULL,
  action_details JSONB,
  performed_by UUID,
  performed_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  affected_client_id UUID,
  affected_portfolio_id UUID,
  compliance_category TEXT,
  regulatory_significance BOOLEAN DEFAULT false,
  ip_address INET,
  user_agent TEXT,
  session_id UUID,
  PRIMARY KEY (id)
);

-- =============================================
-- FOREIGN KEYS
-- =============================================

ALTER TABLE advisors ADD CONSTRAINT advisors_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE clients ADD CONSTRAINT clients_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE clients ADD CONSTRAINT clients_primary_advisor_id_fkey FOREIGN KEY (primary_advisor_id) REFERENCES advisors(id);
ALTER TABLE lisp_platforms ADD CONSTRAINT lisp_platforms_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE portfolios ADD CONSTRAINT portfolios_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE portfolios ADD CONSTRAINT portfolios_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id);
ALTER TABLE portfolios ADD CONSTRAINT portfolios_advisor_id_fkey FOREIGN KEY (advisor_id) REFERENCES advisors(id);
ALTER TABLE portfolios ADD CONSTRAINT portfolios_platform_id_fkey FOREIGN KEY (platform_id) REFERENCES lisp_platforms(id);
ALTER TABLE holdings ADD CONSTRAINT holdings_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE holdings ADD CONSTRAINT holdings_portfolio_id_fkey FOREIGN KEY (portfolio_id) REFERENCES portfolios(id);
ALTER TABLE transactions ADD CONSTRAINT transactions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE transactions ADD CONSTRAINT transactions_portfolio_id_fkey FOREIGN KEY (portfolio_id) REFERENCES portfolios(id);
ALTER TABLE transactions ADD CONSTRAINT transactions_holding_id_fkey FOREIGN KEY (holding_id) REFERENCES holdings(id);
ALTER TABLE portfolio_reports ADD CONSTRAINT portfolio_reports_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE portfolio_reports ADD CONSTRAINT portfolio_reports_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id);
ALTER TABLE portfolio_reports ADD CONSTRAINT portfolio_reports_advisor_id_fkey FOREIGN KEY (advisor_id) REFERENCES advisors(id);
ALTER TABLE portfolio_reports ADD CONSTRAINT portfolio_reports_generated_by_fkey FOREIGN KEY (generated_by) REFERENCES advisors(id);
ALTER TABLE portfolio_reports ADD CONSTRAINT portfolio_reports_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES advisors(id);
ALTER TABLE portfolio_reports ADD CONSTRAINT portfolio_reports_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES advisors(id);
ALTER TABLE fica_submissions ADD CONSTRAINT fica_submissions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE fica_submissions ADD CONSTRAINT fica_submissions_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id);
ALTER TABLE fica_submissions ADD CONSTRAINT fica_submissions_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES advisors(id);
ALTER TABLE fica_submissions ADD CONSTRAINT fica_submissions_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES advisors(id);
ALTER TABLE compliance_audit_log ADD CONSTRAINT compliance_audit_log_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE compliance_audit_log ADD CONSTRAINT compliance_audit_log_affected_client_id_fkey FOREIGN KEY (affected_client_id) REFERENCES clients(id);
ALTER TABLE compliance_audit_log ADD CONSTRAINT compliance_audit_log_affected_portfolio_id_fkey FOREIGN KEY (affected_portfolio_id) REFERENCES portfolios(id);
